# Generated by Django 5.1.4 on 2024-12-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifthubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
